/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.BorderLayout;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class JPanelQuanLiLoTrinh extends javax.swing.JPanel {

    /**
     * Creates new form JPanelQuanLiTau
     */
    public JPanelQuanLiLoTrinh() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnTauDangChay = new javax.swing.JPanel();
        jlbTauDangChay = new javax.swing.JLabel();
        jpnHieuChinh = new javax.swing.JPanel();
        jlbHieuChinh = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 204));

        jpnTauDangChay.setBackground(new java.awt.Color(51, 255, 51));
        jpnTauDangChay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jpnTauDangChayMousePressed(evt);
            }
        });

        jlbTauDangChay.setBackground(new java.awt.Color(51, 255, 51));
        jlbTauDangChay.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jlbTauDangChay.setForeground(new java.awt.Color(255, 255, 255));
        jlbTauDangChay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/baseline_departure_board_white_18dp.png"))); // NOI18N
        jlbTauDangChay.setText("Tàu đang chạy");
        jlbTauDangChay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jlbTauDangChayMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jpnTauDangChayLayout = new javax.swing.GroupLayout(jpnTauDangChay);
        jpnTauDangChay.setLayout(jpnTauDangChayLayout);
        jpnTauDangChayLayout.setHorizontalGroup(
            jpnTauDangChayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnTauDangChayLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jlbTauDangChay, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnTauDangChayLayout.setVerticalGroup(
            jpnTauDangChayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnTauDangChayLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jlbTauDangChay, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jpnHieuChinh.setBackground(new java.awt.Color(102, 102, 255));
        jpnHieuChinh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jpnHieuChinhMousePressed(evt);
            }
        });

        jlbHieuChinh.setBackground(new java.awt.Color(102, 102, 255));
        jlbHieuChinh.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jlbHieuChinh.setForeground(new java.awt.Color(255, 255, 255));
        jlbHieuChinh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/baseline_edit_road_white_18dp.png"))); // NOI18N
        jlbHieuChinh.setText("Hiệu chỉnh");

        javax.swing.GroupLayout jpnHieuChinhLayout = new javax.swing.GroupLayout(jpnHieuChinh);
        jpnHieuChinh.setLayout(jpnHieuChinhLayout);
        jpnHieuChinhLayout.setHorizontalGroup(
            jpnHieuChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnHieuChinhLayout.createSequentialGroup()
                .addGap(0, 17, Short.MAX_VALUE)
                .addComponent(jlbHieuChinh, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpnHieuChinhLayout.setVerticalGroup(
            jpnHieuChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbHieuChinh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(102, 255, 204));

        jLabel3.setBackground(new java.awt.Color(102, 255, 204));
        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("jLabel3");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jpnTauDangChay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jpnHieuChinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jpnHieuChinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpnTauDangChay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(294, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jpnTauDangChayMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnTauDangChayMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpnTauDangChayMousePressed

    private void jlbTauDangChayMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbTauDangChayMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jlbTauDangChayMousePressed

    private void jpnHieuChinhMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnHieuChinhMousePressed
        // TODO add your handling code here:
        this.removeAll();
        this.setLayout(new BorderLayout());
        this.validate();
        this.repaint();
    }//GEN-LAST:event_jpnHieuChinhMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel jlbHieuChinh;
    private javax.swing.JLabel jlbTauDangChay;
    private javax.swing.JPanel jpnHieuChinh;
    private javax.swing.JPanel jpnTauDangChay;
    // End of variables declaration//GEN-END:variables
}
